"""
Real vs Synthetic Classification Dataset
For training CNN to distinguish real from synthetic chest X-rays
Binary classification: 0 = Real, 1 = Synthetic
"""
import torch
import os
from torch.utils.data import Dataset
from PIL import Image
from pathlib import Path
import warnings


class XrayDataset(Dataset):
    """
    Dataset for Real vs Synthetic binary classification
    
    Combines:
    - Real images from Domain A (No Finding) and Domain B (Pneumothorax)
    - Synthetic images generated by CycleGAN
    
    Args:
        real_images_dir: Directory containing real images
        synthetic_images_dir: Directory containing synthetic images
        list_A: Path to Domain A split file (e.g., train_A.txt)
        list_B: Path to Domain B split file (e.g., train_B.txt)
        transform: Torchvision transforms to apply
    """
    
    def __init__(self, real_images_dir, synthetic_images_dir, list_A, list_B, transform=None):
        self.real_images_dir = Path(real_images_dir)
        self.synthetic_images_dir = Path(synthetic_images_dir)
        self.transform = transform
        
        # Store all samples as (path, label) tuples
        self.samples = []
        
        print(f"📂 Building Real vs Synthetic dataset...")
        
        # Load real images from Domain A
        print(f"   Loading Domain A (No Finding)...")
        with open(list_A, "r") as f:
            filenames_A = [line.strip() for line in f if line.strip()]
        
        real_count_A = 0
        for filename in filenames_A:
            img_path = self.real_images_dir / filename
            if img_path.exists():
                self.samples.append((str(img_path), 0))  # Label 0 = Real
                real_count_A += 1
        
        print(f"      Real images (Domain A): {real_count_A}")
        
        # Load real images from Domain B
        print(f"   Loading Domain B (Pneumothorax)...")
        with open(list_B, "r") as f:
            filenames_B = [line.strip() for line in f if line.strip()]
        
        real_count_B = 0
        for filename in filenames_B:
            img_path = self.real_images_dir / filename
            if img_path.exists():
                self.samples.append((str(img_path), 0))  # Label 0 = Real
                real_count_B += 1
        
        print(f"      Real images (Domain B): {real_count_B}")
        
        # Load synthetic images
        print(f"   Loading synthetic images...")
        synthetic_count = 0
        
        if self.synthetic_images_dir.exists():
            for img_file in sorted(self.synthetic_images_dir.glob("*.png")):
                self.samples.append((str(img_file), 1))  # Label 1 = Synthetic
                synthetic_count += 1
        else:
            warnings.warn(f"Synthetic directory not found: {self.synthetic_images_dir}")
        
        print(f"      Synthetic images: {synthetic_count}")
        
        # Verify we have samples
        if not self.samples:
            raise RuntimeError("No valid images found in dataset!")
        
        # Final statistics
        total_real = real_count_A + real_count_B
        print(f"\n📊 Dataset statistics:")
        print(f"   Total samples: {len(self.samples)}")
        print(f"   Real images: {total_real} ({total_real / len(self.samples) * 100:.1f}%)")
        print(f"   Synthetic images: {synthetic_count} ({synthetic_count / len(self.samples) * 100:.1f}%)")
        
        if total_real == 0 or synthetic_count == 0:
            warnings.warn("⚠️  Dataset is imbalanced (missing one class)!")
    
    def __len__(self):
        return len(self.samples)
    
    def __getitem__(self, idx):
        """
        Returns:
            image: Transformed PIL Image
            label: Binary label (0=Real, 1=Synthetic)
        """
        img_path, label = self.samples[idx]
        
        try:
            # Load image as RGB (CNN expects 3 channels)
            img = Image.open(img_path).convert("RGB")
            
            # Apply transforms
            if self.transform:
                img = self.transform(img)
            
            return img, label
        
        except Exception as e:
            warnings.warn(f"Error loading {img_path}: {e}")
            
            # Fallback: try next image
            next_idx = (idx + 1) % len(self.samples)
            return self.__getitem__(next_idx)


def test_dataset():
    """Test dataset loading"""
    from torchvision import transforms
    from torch.utils.data import DataLoader
    
    transform = transforms.Compose([
        transforms.Resize((256, 256)),
        transforms.ToTensor(),
        transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])
    ])
    
    dataset = XrayDataset(
        real_images_dir="D:/ChestXray_GAN_CNN_ViT/data/chestxray/images",
        synthetic_images_dir="generated_images/synthetic_pneumothorax",
        list_A="D:/ChestXray_GAN_CNN_ViT/data/chestxray/splits/pneumothorax/train_A.txt",
        list_B="D:/ChestXray_GAN_CNN_ViT/data/chestxray/splits/pneumothorax/train_B.txt",
        transform=transform
    )
    
    loader = DataLoader(dataset, batch_size=4, shuffle=True, num_workers=0)
    
    print(f"\n🧪 Testing dataset...")
    images, labels = next(iter(loader))
    
    print(f"   Batch shape: {images.shape}")
    print(f"   Labels: {labels}")
    print(f"   Label distribution: {labels.sum().item()} synthetic, {(labels == 0).sum().item()} real")
    print(f"✅ Dataset test passed!")


if __name__ == "__main__":
    test_dataset()
